name: Deploy Function App

on:
  push:
    branches:
      - main
    paths:
      - "function/**"
      - ".github/workflows/**"

permissions:
  contents: read
  id-token: write

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: function/go.mod
          cache-dependency-path: function/go.sum

      - name: Install dependencies
        working-directory: function
        run: go mod download

      - name: Build binary
        working-directory: function
        run: CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -o ./bin/main ./src/main.go

      - name: Upload binary
        uses: actions/upload-artifact@v6
        with:
          name: function-artifact
          if-no-files-found: error
          include-hidden-files: true # to include .funcignore file
          path: |
            function/bin
            function/host.json
            function/.funcignore
            function/**/function.json

  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: build
    steps:
      ## We have to use the RBAC authentication method to force action Azure/functions-action@v1 to deploy via RUN_FROM_PACKAGE
      - name: Azure Login
        uses: azure/login@v2
        with:
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Download binary
        uses: actions/download-artifact@v6
        with:
          name: function-artifact

      - name: Set execute permission on binary
        run: chmod +x ./bin/main

      - name: Show local directory
        run: ls -laR

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
          respect-funcignore: true
