name: Run tests

on:
  push:
    branches:
      - main
      - feature/**
      - dependabot/**
    paths:
      - 'function/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: function/go.mod
          cache-dependency-path: function/go.sum

      - name: Install dependencies
        working-directory: function
        run: go mod download

      # - name: Start containers
      #   working-directory: function
      #   run: docker-compose -f docker-compose.yaml up -d --wait --build

      - name: Run tests
        working-directory: function
        run: go test ./... >> $GITHUB_STEP_SUMMARY

      # - name: Stop containers
      #   if: always()
      #   working-directory: function
      #   run: docker-compose -f docker-compose.yaml down --volumes
